// Code generated by goctl. DO NOT EDIT.
package types

type PostsCommentRequest struct {
	PostsIdentity string `json:"posts_identity"`
}

type PostsCommentReply struct {
	List []PostsCommentsItem `json:"list"`
}

type PostsFeedbackCreateRequest struct {
	Type          string `json:"type"`
	PostsIdentity string `json:"posts_identity"`
}

type PostsFeedbackCreateReply struct {
	Ilike   int `json:"ilike"`
	Dislike int `json:"dislike"`
	Collect int `json:"collect"`
}

type GongDeUpdateRequest struct {
	CurrentCount int `json:"current_count"`
}

type GongDeUpdateReply struct {
	Count int `json:"count"`
}

type PostsCreateRequest struct {
	Title   string `json:"title"`
	Tags    string `json:"tags,optional"`
	Content string `json:"content,optional"`
	Mention string `json:"mention,optional"`
	Cover   string `json:"cover,optional"`
}

type PostsCreateReply struct {
}

type PostsUpdateRequest struct {
	Identity string `json:"identity"`
	Title    string `json:"title,optional"`
	Tags     string `json:"tags,optional"`
	Content  string `json:"content,optional"`
	Mention  string `json:"mention,optional"`
	Cover    string `json:"cover,optional"`
}

type PostsUpdateReply struct {
}

type PostsDeleteRequest struct {
	Identity string `json:"identity"`
}

type PostsDeleteReply struct {
}

type PostsDetailRequest struct {
	Identity string `json:"identity"`
}

type PostsDetailReply struct {
	Identity   string `json:"identity"`
	Title      string `json:"title"`
	Tags       string `json:"tags"`
	Content    string `json:"content"`
	Mention    string `json:"mention"`
	Cover      string `json:"cover"`
	Ilike      int    `json:"ilike"`
	Dislike    int    `json:"dislike"`
	Collection int    `json:"collection"`
	ClickNum   int    `json:"click_num"`
	Owner      string `json:"owner"`
	Avatar     string `json:"avatar"`
	UpdatedAt  string `json:"updated_at"`
}

type PostsCommentCreateRequest struct {
	Content       string `json:"content"`
	Mention       string `json:"mention,optional"`
	ReplyIdentity string `json:"reply_identity,optional"`
	PostsIdentity string `json:"posts_identity"`
	ReplyName     string `json:"reply_name,optional"`
}

type PostsCommentCreateReply struct {
}

type PostsCommentDeleteRequest struct {
	Identity string `json:"identity"`
}

type PostsCommentDeleteReply struct {
}

type PostsListRequest struct {
	Id   int64 `json:"id,optional"`
	Page int   `json:"page,optional"`
	Size int   `json:"size,optional"`
}

type PostsListReply struct {
	List []*PostsListItem `json:"list"`
}

type PostsListItem struct {
	Identity  string `json:"identity"`
	Title     string `json:"title"`
	Tags      string `json:"tags"`
	Content   string `json:"content"`
	Mention   string `json:"mention"`
	Cover     string `json:"cover"`
	ClickNum  int    `json:"click_num"`
	Owner     string `json:"owner"`
	Avatar    string `json:"avatar"`
	ReplyNum  int    `json:"reply_num"`
	UpdatedAt string `json:"updated_at"`
}

type PostsCommentsRequest struct {
	PostsIdentity string `json:"posts_identity"`
}

type PostsCommentsReply struct {
	List []*PostsCommentsItem `json:"list"`
}

type PostsCommentsItem struct {
	Identity      string `json:"identity"`
	ReplyIdentity string `json:"reply_identity"`
	PostsIdentity string `json:"posts_identity"`
	PostsName     string `json:"posts_name"`
	ReplyName     string `json:"reply_name"`
	Content       string `json:"content"`
	Mention       string `json:"mention"`
	Owner         string `json:"owner"`
	OwnerIdentity string `json:"owner_identity"`
	Avatar        string `json:"avatar"`
	Like          int    `json:"like"`
	Dislike       int    `json:"dislike"`
	UpdatedAt     string `json:"updated_at"`
}
