// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"cloud-disk/common/globalkey"
	"cloud-disk/common/xerr"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	storeFieldNames          = builder.RawFieldNames(&Store{})
	storeRows                = strings.Join(storeFieldNames, ",")
	storeRowsExpectAutoSet   = strings.Join(stringx.Remove(storeFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	storeRowsWithPlaceHolder = strings.Join(stringx.Remove(storeFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheCloudDiskStoreIdPrefix = "cache:cloudDisk:store:id:"
)

type (
	storeModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Store) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Store, error)
		Update(ctx context.Context, session sqlx.Session, data *Store) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Store) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultStoreModel struct {
		sqlc.CachedConn
		table string
	}

	Store struct {
		Id          int64     `db:"id"`           // 文件仓库ID
		UserId      int64     `db:"user_id"`      // 主人ID
		CurrentSize int64     `db:"current_size"` // 当前容量（单位KB）
		MaxSize     int64     `db:"max_size"`     // 最大容量（单位KB）
		DelState    int64     `db:"del_state"`
		DeleteTime  time.Time `db:"delete_time"`
		Version     int64     `db:"version"` // 乐观锁版本号
	}
)

func newStoreModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultStoreModel {
	return &defaultStoreModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`store`",
	}
}

func (m *defaultStoreModel) Insert(ctx context.Context, session sqlx.Session, data *Store) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	cloudDiskStoreIdKey := fmt.Sprintf("%s%v", cacheCloudDiskStoreIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, storeRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.CurrentSize, data.MaxSize, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.CurrentSize, data.MaxSize, data.DelState, data.DeleteTime, data.Version)
	}, cloudDiskStoreIdKey)
}

func (m *defaultStoreModel) FindOne(ctx context.Context, id int64) (*Store, error) {
	cloudDiskStoreIdKey := fmt.Sprintf("%s%v", cacheCloudDiskStoreIdPrefix, id)
	var resp Store
	err := m.QueryRowCtx(ctx, &resp, cloudDiskStoreIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", storeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStoreModel) Update(ctx context.Context, session sqlx.Session, data *Store) (sql.Result, error) {
	cloudDiskStoreIdKey := fmt.Sprintf("%s%v", cacheCloudDiskStoreIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, storeRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.CurrentSize, data.MaxSize, data.DelState, data.DeleteTime, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.CurrentSize, data.MaxSize, data.DelState, data.DeleteTime, data.Version, data.Id)
	}, cloudDiskStoreIdKey)
}

func (m *defaultStoreModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Store) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	cloudDiskStoreIdKey := fmt.Sprintf("%s%v", cacheCloudDiskStoreIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, storeRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.CurrentSize, data.MaxSize, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.CurrentSize, data.MaxSize, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
	}, cloudDiskStoreIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return xerr.NewErrCode(xerr.DB_UPDATE_AFFECTED_ZERO_ERROR)
	}

	return nil
}

func (m *defaultStoreModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	cloudDiskStoreIdKey := fmt.Sprintf("%s%v", cacheCloudDiskStoreIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, cloudDiskStoreIdKey)
	return err
}

func (m *defaultStoreModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheCloudDiskStoreIdPrefix, primary)
}
func (m *defaultStoreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", storeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultStoreModel) tableName() string {
	return m.table
}
