// Code generated by goctl. DO NOT EDIT!
// Source: verification.proto

package server

import (
	"context"

	"trytry/app/verification/cmd/rpc/internal/logic"
	"trytry/app/verification/cmd/rpc/internal/svc"
	"trytry/app/verification/cmd/rpc/pb"
)

type VerificationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVerificationServer
}

func NewVerificationServer(svcCtx *svc.ServiceContext) *VerificationServer {
	return &VerificationServer{
		svcCtx: svcCtx,
	}
}

func (s *VerificationServer) VerifyEmail(ctx context.Context, in *pb.VerifyEmailReq) (*pb.VerifyEmailResp, error) {
	l := logic.NewVerifyEmailLogic(ctx, s.svcCtx)
	return l.VerifyEmail(in)
}

func (s *VerificationServer) VerifyImage(ctx context.Context, in *pb.VerifyImageReq) (*pb.VerifyImageResp, error) {
	l := logic.NewVerifyImageLogic(ctx, s.svcCtx)
	return l.VerifyImage(in)
}
