// Code generated by goctl. DO NOT EDIT!
// Source: verification.proto

package verification

import (
	"context"

	"trytry/app/verification/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	VerifyEmailReq  = pb.VerifyEmailReq
	VerifyEmailResp = pb.VerifyEmailResp
	VerifyImageReq  = pb.VerifyImageReq
	VerifyImageResp = pb.VerifyImageResp

	Verification interface {
		VerifyEmail(ctx context.Context, in *VerifyEmailReq, opts ...grpc.CallOption) (*VerifyEmailResp, error)
		VerifyImage(ctx context.Context, in *VerifyImageReq, opts ...grpc.CallOption) (*VerifyImageResp, error)
	}

	defaultVerification struct {
		cli zrpc.Client
	}
)

func NewVerification(cli zrpc.Client) Verification {
	return &defaultVerification{
		cli: cli,
	}
}

func (m *defaultVerification) VerifyEmail(ctx context.Context, in *VerifyEmailReq, opts ...grpc.CallOption) (*VerifyEmailResp, error) {
	client := pb.NewVerificationClient(m.cli.Conn())
	return client.VerifyEmail(ctx, in, opts...)
}

func (m *defaultVerification) VerifyImage(ctx context.Context, in *VerifyImageReq, opts ...grpc.CallOption) (*VerifyImageResp, error) {
	client := pb.NewVerificationClient(m.cli.Conn())
	return client.VerifyImage(ctx, in, opts...)
}
