// Code generated by goctl. DO NOT EDIT.
package types

type VerifyEmailReq struct {
	Email string `json:"email"`
}

type VerifyEmailResp struct {
}

type VerifyImageReq struct {
}

type VerifyImageResp struct {
	ImageUrl string `json:"imageurl"`
}
