// Code generated by goctl. DO NOT EDIT.
package types

type FileDetail struct {
	Path     string `json:"path",default:"/"`
	FileName string `json:"fileName"`
	Size     int64  `json:"size"`
}

type UploadCertificateReq struct {
	Files []FileDetail `json:"files"`
}

type UploadCertificateResp struct {
	Certificate string `json:"certificate""`
}

type DownloadCertificateReq struct {
}

type DownloadCertificateResp struct {
	Certificate string `json:"certificate""`
}

type CallbackReq struct {
}

type CallbackResp struct {
}

type Folder struct {
	Id         int64 `json:"id"`
	FolderName int64 `json:"folderName"`
	UpdateTime int64 `json:"updateTime"`
	CreateTime int64 `json:"createTime"`
}

type File struct {
	Id             int64  `json:"id"`
	FileName       string `json:"fileName"`
	FilePath       string `json:"filePath"`
	Size           int64  `json:"size"`
	Postfix        string `json:"postfix"`
	DownloadNumber int64  `json:"downloadNumber"`
	UpdateTime     int64  `json:"updateTime"`
	CreateTime     int64  `json:"createTime"`
}

type CreateFolderReq struct {
	Path       string `json:"path"`
	FolderName string `json:"folderName"`
}

type CreateFolderResp struct {
	CreateTime int64 `json:"create_time"`
}

type ListReq struct {
	Path string `json:"path"`
}

type ListResp struct {
	FolderList []Folder `json:"folderList"`
	FileList   []File   `json:"fileList"`
}

type MovedReq struct {
	Id       int64  `json:"id"`
	IsFile   bool   `json:"isFile"`
	Name     string `json:"name"`
	SrcPath  string `json:"srcPath"`
	DestPath string `json:"destPath"`
}

type MovedResp struct {
}

type StoreDetailReq struct {
}

type StoreDetailResp struct {
	CurrentSize int64 `json:"current_size"`
	MaxSize     int64 `json:"max_size"`
}
