// Code generated by goctl. DO NOT EDIT.
package types

type FileDetail struct {
	Pid      int64  `json:"pid",default:"0"`
	FileName string `json:"fileName"`
	Size     int64  `json:"size"`
}

type UploadCertificateReq struct {
	Files []FileDetail `json:"files"`
}

type UploadCertificateResp struct {
	Certificate string `json:"certificate""`
}

type DownloadCertificateReq struct {
	Id int64 `json:"id"`
}

type DownloadCertificateResp struct {
	DownloadUrl string `json:"downloadUrl"`
}

type CallbackReq struct {
}

type CallbackResp struct {
}

type KindReq struct {
	Kind string `json:"kind"`
}

type KindResp struct {
	Files []FileDetail `json:"files"`
}

type Folder struct {
	Id         int64 `json:"id"`
	FolderName int64 `json:"folderName"`
	UpdateTime int64 `json:"updateTime"`
	CreateTime int64 `json:"createTime"`
}

type File struct {
	Id             int64  `json:"id"`
	FileName       string `json:"fileName"`
	Size           int64  `json:"size"`
	Postfix        string `json:"postfix"`
	DownloadNumber int64  `json:"downloadNumber"`
	UpdateTime     int64  `json:"updateTime"`
	CreateTime     int64  `json:"createTime"`
}

type CreateFolderReq struct {
	Pid        int64  `json:"pid"`
	FolderName string `json:"folderName"`
}

type CreateFolderResp struct {
	ID         int64 `json:"id"`
	CreateTime int64 `json:"create_time"`
}

type ListReq struct {
	Pid int64 `json:"pid"`
}

type ListResp struct {
	FolderList []Folder `json:"folderList"`
	FileList   []File   `json:"fileList"`
}

type MovedReq struct {
	Id     int64  `json:"id"`
	IsFile bool   `json:"isFile"`
	Name   string `json:"name"`
	ToPid  int64  `json:"toPid"`
}

type MovedResp struct {
}

type StoreDetailReq struct {
}

type StoreDetailResp struct {
	CurrentSize int64 `json:"currentSize"`
	MaxSize     int64 `json:"maxSize"`
}
