// Code generated by goctl. DO NOT EDIT!
// Source: disk.proto

package server

import (
	"context"

	"cloud-disk/app/disk/cmd/rpc/internal/logic"
	"cloud-disk/app/disk/cmd/rpc/internal/svc"
	"cloud-disk/app/disk/cmd/rpc/pb"
)

type DiskServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDiskServer
}

func NewDiskServer(svcCtx *svc.ServiceContext) *DiskServer {
	return &DiskServer{
		svcCtx: svcCtx,
	}
}

// store 详情
func (s *DiskServer) DetailStore(ctx context.Context, in *pb.StoreDetailReq) (*pb.StoreDetailResp, error) {
	l := logic.NewDetailStoreLogic(ctx, s.svcCtx)
	return l.DetailStore(in)
}

// 修改store大小
func (s *DiskServer) ChangeStore(ctx context.Context, in *pb.ChangeStoreReq) (*pb.ChangeStoreResp, error) {
	l := logic.NewChangeStoreLogic(ctx, s.svcCtx)
	return l.ChangeStore(in)
}

// 获取路径下的文件和文件夹
func (s *DiskServer) ListFolders(ctx context.Context, in *pb.ListFolderReq) (*pb.ListFolderResp, error) {
	l := logic.NewListFoldersLogic(ctx, s.svcCtx)
	return l.ListFolders(in)
}
