// Code generated by goctl. DO NOT EDIT!
// Source: disk.proto

package server

import (
	"context"

	"cloud-disk/app/disk/cmd/rpc/internal/logic"
	"cloud-disk/app/disk/cmd/rpc/internal/svc"
	"cloud-disk/app/disk/cmd/rpc/pb"
)

type StoreServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStoreServer
}

func NewStoreServer(svcCtx *svc.ServiceContext) *StoreServer {
	return &StoreServer{
		svcCtx: svcCtx,
	}
}

// 判断是否能存入
func (s *StoreServer) StoreDetail(ctx context.Context, in *pb.StoreDetailReq) (*pb.StoreDetailResp, error) {
	l := logic.NewStoreDetailLogic(ctx, s.svcCtx)
	return l.StoreDetail(in)
}

// 改变store大小
func (s *StoreServer) ChangeStore(ctx context.Context, in *pb.ChangeStoreReq) (*pb.ChangeStoreResp, error) {
	l := logic.NewChangeStoreLogic(ctx, s.svcCtx)
	return l.ChangeStore(in)
}
