// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Identity int64  `json:"identity"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Sex      string `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
	Capacity int    `json:"capacity"`
	CreateAt string `json:"create_at"`
}

type RegisterReq struct {
	Name     string `json:"name""`
	Email    string `json:"email"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"AccessExpire"`
	RefreshAfter int64  `json:"RefreshAfter"`
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`
	IV            string `json:"iv"`
	EncryptedData string `json:"encryptedData"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
